### ISSUE TITLE
Lab 02: Can't save Anti-spam policy

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/MS-220T00-Troubleshoot-Microsoft-Exchange-Online#13]
#### Step: 11

When saving the anti-spam policy, a popup window was displayed asking if I wanted to enable customization for my organization and that it could take 24-48 hours to complete. I selected "Yes" and a couple minutes later received the following error
![Screenshot 2023-04-18 at 7 28 07 AM](https://user-images.githubusercontent.com/48496971/232780777-c361fa15-bd5f-4739-aa54-3bcd1dd6c977.png)

Repro steps:

1. Attempt to complete Task 1

**Comment by maquinl** [comment]
@AMorin8787 thank you for bringing this to our attention. I will review and reach back out with more information.

**Comment by maquinl** [comment]
@AMorin8787 I believe i have found a solution and have included new steps (2-5) at the start of the task to enable organization customization which should resolve this error. Feel free to test the new steps and let me know if you have any other issues. 

Thanks!
